### ISSUE TITLE
Naming inconsistency of Swagger Auth Scopes

### ISSUE THREAD

**Issue by Ken1Nil** [pdevito3/craftsman#119]
When scaffolding a project with ProjectName (for example: "MyCraftsmanManagement") containing PascalCase naming style, and not supplying a PolicyName in Template, SwaggerBuilder makes the Scope name "my_craftsman_management" with `ProjectName.Underscore()`.

This ignores whatever is used in 
```
Environment:
    AuthSettings: 
       Audience: craftsman_management
```

Would be helpful if the Scopes for Swagger Auth Documentation would use the Audience: property instead of MyProjectName -> my_project_name 

### Steps to reproduce

Using this template you can generate the same:

```
DomainName: MyCraftsmanManagementWithAuth
BoundedContexts:
- ProjectName: MyCraftsmanManagement
  Port: 5375
  DbContext:
    ContextName: MyCraftsmanDbContext
    DatabaseName: MyCraftsmanManagement
    Provider: postgres
  Entities:
  - Name: Craft
    Features:
    - Type: GetList
      IsProtected: true
      PermissionName: CanReadCrafts
    Properties:
    - Name: Name
      Type: string
      CanFilter: true
      CanSort: true
  Environment:
    AuthSettings:
      Authority: http://localhost:3255/realms/DevRealm
      Audience: craftsman_management
      AuthorizationUrl: http://localhost:3255/realms/DevRealm/protocol/openid-connect/auth
      TokenUrl: http://localhost:3255/realms/DevRealm/protocol/openid-connect/token
      ClientId: craftsman_management.swagger
      ClientSecret: 974d6f71-d41b-4601-9a7a-a33081f80687
    BrokerSettings:
        Host: localhost
        VirtualHost: /
        Username: guest
        Password: guest
  SwaggerConfig:
      Title: MyCraftsmanManagement API
      SwaggerEndpointName: MyCraftsmanManagement API
      AddSwaggerComments: true

```

### Further technical details

Craftsman version (`dotnet tool list -g`):
craftsman        0.21.1
