### ISSUE TITLE
Author cannot be null

### ISSUE THREAD

**Issue by AlexanderNZ** [pdevito3/craftsman#122]
Hi there,

Just letting you know that I'm seeing the same issue reported here https://github.com/pdevito3/craftsman/issues/72#issuecomment-1103115068 - but on Mac

### Steps to reproduce

On Mac Ventura 13.5.1 with Craftsman 0.22.1 create a yml file with contents:

```yml
DomainName: poc
BoundedContexts:
    - ProjectName: HumanContext
      Port: 8081
      DbContext:
        ContextName: HumanDbContext
        DatabaseName: HumanReadModel
        Provider: postgres
        NamingConvention: CamelCase
      Entities:
        - Name: Human
          Features:
            - Type: AddRecord
            - Type: GetRecord
            - Type: GetList
            - Type: UpdateRecord
            - Type: DeleteRecord
          Properties:
          - Name: PropertyName
            Type: string
            IsRequired: true
          - Name: lastName
            Type: string
            IsRequired: true
          - Name: irdNumber
            Type: int
            IsRequired: false
          - Name: activeContracts
            Relationship: 1tomany
            ForeignEntityName: Contract
            ForeignEntityPlural: Contracts
        - Name: Contract
          Features:
            - Type: AddRecord
            - Type: GetRecord
            - Type: GetList
            - Type: UpdateRecord
            - Type: DeleteRecord
          Properties:
          - Name: jobTitle
            Type: string
            IsRequired: true
          - Name: hourlyRate
            Type: int
            IsRequired: true
          - Name: contractedHoursPerUnitTime
            Type: int
            IsRequired: false
          - Name: unitTime
            SmartNames:
                - week
                - month
                - year
```

Run `craftsman new domain poc.yml`
Craftsman outputs an error `Error: Value cannot be null. (Parameter 'author')`
