### ISSUE TITLE
Use with basic Test Yaml  fails 

### ISSUE THREAD

**Issue by barnybadzoo** [pdevito3/craftsman#19]
Hi,

i really like wrapt.dev and would like to test it with this simple setup:

On my workstation mystation i use a sqlexpress instance like a normal sqlserver.I did also create a database test.
I did test craftman with this yaml file:

----------------
```
SolutionName: Test.Api
DbContext:
  ContextName: TestDbContext
  DatabaseName: test
  Provider: SqlServer
Entities:
- Name: Info
  Properties:
  - Name: InfoId
    IsPrimaryKey: true
    Type: int
    CanFilter: true
    CanSort: true
  - Name: MyInfo
    Type: string
    CanFilter: true
    CanSort: true
  - Name: MySpeed
    Type: int
    CanFilter: true
    CanSort: true
  - Name: MyType
    Type: string
    CanFilter: true
    CanSort: true
Environments:
  - EnvironmentName: Startup
    ConnectionString: "Data Source=mystation\\sqlexpress;Database=test;Integrated Security=false;User ID=sa;Password=start;"
    ProfileName: Prod     
SwaggerConfig:
  Title: Test WebApi
  Description: Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body. API Documentation is at xxxxx/dev/docs
  AddSwaggerComments: true
```
----------------

I do only get a message "Your template file was parsed successfully." but it stucks here and does not complete..
Is there way to enable verbose debugging, so i can see where the problem resists ?
