### ISSUE TITLE
Your solution name can not match an entity name. This will cause namespace issues in your project.

### ISSUE THREAD

**Issue by znedw** [pdevito3/craftsman#22]
Using https://wrapt.dev/docs/tutorial `Environment and Swagger Setup`

Your solution name can not match an entity name. This will cause namespace issues in your project.

### Steps to reproduce
```
~/work/wrapt-demo
❯ craftsman --version
v0.9.2.0

~/work/wrapt-demo
❯ craftsman new:domain .\wrap-templates\Test.yaml
Your template file was parsed successfully.
Your solution name can not match an entity name. This will cause namespace issues in your project.
```

`Test.yaml`
```
DomainName: CarbonKitchen
BoundedContexts:
- SolutionName: Recipes
  Port: 5005
  DbContext:
   ContextName: RecipesDbContext
   DatabaseName: RecipesDbContext
   Provider: SqlServer
  Entities:
  - Name: Recipe
    Properties:
    - Name: RecipeId
      IsPrimaryKey: true
      Type: int
      CanFilter: true
      CanSort: true
    - Name: Title
      Type: string
      CanFilter: true
      CanSort: true
    - Name: Directions
      Type: string
      CanFilter: true
      CanSort: true
    - Name: RecipeSourceLink
      Type: string
      CanFilter: true
      CanSort: true
    - Name: Description
      Type: string
      CanFilter: true
      CanSort: true
    - Name: ImageLink
      Type: string
      CanFilter: true
      CanSort: true
  - Name: Ingredient
    Properties:
    - Name: IngredientId
      IsPrimaryKey: true
      Type: int
      CanFilter: true
      CanSort: true
    - Name: RecipeId
      Type: int?
      CanFilter: true
      CanSort: true
    - Name: Name
      Type: string
      CanFilter: true
      CanSort: true
    - Name: Unit
      Type: string
      CanFilter: true
      CanSort: true
    - Name: Amount
      Type: double?
      CanFilter: true
      CanSort: true
  Environments:
    - EnvironmentName: Production
      ConnectionString: "Data Source=myprodserver;Initial Catalog=CarbonKitchen;Integrated Security=True;Encrypt=True;TrustServerCertificate=True;"
      ProfileName: Prod
    - EnvironmentName: Qa
      ConnectionString: "Data Source=myqaserver;Initial Catalog=CarbonKitchen;Integrated Security=True;Encrypt=True;TrustServerCertificate=True;"
      ProfileName: Qa
  SwaggerConfig:
    Title: Carbon Kitchen Recipes
    Description: Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body. API Documentation is at carbonkitchen.com/dev/docs
    AddSwaggerComments: true
    ApiContact: 
      Name: Carbon Kitchen
      Email: devsupport@CarbonKitchen.com
      Url: https://www.carbonkitchen.com
```
