### ISSUE TITLE
Bootstrapping new project with yaml file fails with unhelpful error (missing directory)

### ISSUE THREAD

**Issue by Insire** [pdevito3/craftsman#4]
Wanted to try this out and followed the tutorial. Wrote this yaml file:
```yaml
SolutionName: SoftThornApi
DbContext:
 ContextName: SoftThornDbContext
 DatabaseName: SoftThorn
 Provider: SqlServer
Entities:
- Name: Product
  Properties:
  - Name: ProductId
    IsPrimaryKey: true
    Type: int
    CanFilter: true
    CanSort: true
  - Name: Name
    Type: string
    CanFilter: true
    CanSort: true
  - Name: ProductImageId
    IsPrimaryKey: false
    Type: int?
    CanFilter: true
    CanSort: false
- Name: ProductImage
  Properties:
  - Name: ProductImageId
    IsPrimaryKey: true
    Type: int
    CanFilter: true
    CanSort: true
  - Name: Image
    Type: byte[]
    CanFilter: false
    CanSort: false
Environments:
  - EnvironmentName: Production
    ConnectionString: "Data Source=myprodserver;Initial Catalog=CarbonKitchen;Integrated Security=True;Encrypt=True;TrustServerCertificate=True;"
    ProfileName: Prod
  - EnvironmentName: Qa
    ConnectionString: "Data Source=myqaserver;Initial Catalog=CarbonKitchen;Integrated Security=True;Encrypt=True;TrustServerCertificate=True;"
    ProfileName: Qa
SwaggerConfig:
  Title: SoftThorn
  Description: Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body. API Documentation is at carbonkitchen.com/dev/docs
  ApiContact: 
    Name: SoftThorn
    Email: support@SoftThorn.com
    Url: localhost
```

### Steps to reproduce

- install the tool
- install template
- update tool
- update template
- write yaml file
- run ``craftsman new:api D:\Drop\Desktop\SoftThorn.yaml``
- somehow missing template?

cli output:
```
An unhandled exception occurred when running the API command.
The error details are:
The `E:\Code\SoftThorn\SoftThornApi\Domain\Entities` directory could not be found.
```

When creating that folder manually, it complains that the folder already exists.

### Further technical details

Craftsman version (`dotnet tool list -g`): craftsman           0.4.2        craftsman     
Foundation version (`dotnet new -u`): wasnt isntalled for some reason

**Comment by pdevito3** [comment]
Hey, can look at this later in more detail, but it looks like you don't have the Foundation template installed which is required to make the base project. You can install it with this command `dotnet new -i foundation.api`. 

That should have you good to go. Remember trying to add an error handler for this and it wasn't as easy as I'd like but will try and look into again. 

Want to eliminate the template all together at some point so maybe I'll do that sooner than later. 

Regardless, try installing foundation and let me know if you're still getting the issue.

**Comment by pdevito3** [comment]
Hey, i just tried installing it with that command and it was spotty for some reason... try this more explicit version `dotnet new --install Foundation.Api::0.3.0`

**Comment by Insire** [comment]
Hi. Thanks for looking into this. I figured out that the template was missing already. Seems like i wasnt very clear on that. So that part works. 

Sadly running the command ``craftsman new:api D:\Drop\Desktop\SoftThorn.yaml`` doesnt seem to finish? How long should i wait for this?

**Comment by Insire** [comment]
Aaaaand my powershell instance just newer rendered the latest output.... nvm me. it seems to be working

**Comment by pdevito3** [comment]
great! good luck. let me know if you have any feedback as you're working on it. 

going to close this ticket.

**Comment by Insire** [comment]
Should i update this ticket going forward, or open a new one each time, because i found the next thing already 😅

**Comment by pdevito3** [comment]
lol, dang! if it's related then yeah open this guy back up. if not, you can do a new one so we're not mixing up issues

**Comment by Insire** [comment]
> 
> 
> lol, dang! if it's related then yeah open this guy back up. if not, you can do a new one so we're not mixing up issues

Hm, i dont think i can reopen it. Atleast i dont see an obvious button to do that.

Anyway.

```yaml
SolutionName: SoftThornApi
DbContext:
 ContextName: SoftThornDbContext
 DatabaseName: SoftThorn
 Provider: SqlServer
Entities:
- Name: Product
  Properties:
  - Name: ProductId
    IsPrimaryKey: true
    Type: int
    CanFilter: true
    CanSort: true
  - Name: Name
    Type: string
    CanFilter: true
    CanSort: true
  - Name: ProductImageId
    IsPrimaryKey: false
    Type: int?
    CanFilter: true
    CanSort: false
- Name: ProductImage
  Properties:
  - Name: ProductImageId
    IsPrimaryKey: true
    Type: int
    CanFilter: true
    CanSort: true
  - Name: Image
    Type: byte[]
    CanFilter: false
    CanSort: false
```
i shortened my yaml file a bit, to pretty much only generate entities and use sqlserver. But for some reason, there is postgres sql included there too. Which i dont need and dont have installed, so my build fails.

![grafik](https://user-images.githubusercontent.com/11455827/102138183-41654000-3e5c-11eb-9bb4-1665be3a9bc3.png)
