### ISSUE TITLE
Should paginated results have a default sort order?

### ISSUE THREAD

**Issue by nm777** [pdevito3/craftsman#9]
When using a MSSQL server for the database back-end and hitting a base route for an entity, entity framework gives the following warning:

```
warn: Microsoft.EntityFrameworkCore.Query[10102]
      The query uses a row limiting operator ('Skip'/'Take') without an 'OrderBy' operator. This may lead to unpredictable results.
```

Here is an example reproduction:

1. Set up a local MSSQL server and create a database with the name ExampleDb.

2. Adjust the MSSQL username and password below, and save the following `Example.API.yaml` file.
```
SolutionName: Example.API
AddGit: false

DbContext:
 ContextName: ExampleDbContext
 DatabaseName: ExampleDb
 Provider: SqlServer

Entities:
- Name: MyEntity
  Properties:
  - Name: MyEntityId
    IsPrimaryKey: true
    Type: int
    CanFilter: true
    CanSort: true
  - Name: Title
    Type: string
    CanFilter: true
    CanSort: true

Environments:
  - EnvironmentName: Local
    ConnectionString: "Data Source=localhost;Initial Catalog=ExampleDb;User Id=sa;Password=P@$$w0rd;"
    ProfileName: Local
```

3. Executing the following shell commands creates the API, creates and runs database migrations, and starts the API service:
```
echo 'n' | craftsman new:api ${PROJECT_NAME}.yaml
echo ""
cd Example.API
export ASPNETCORE_ENVIRONMENT=Local
dotnet ef migrations add "InitialMigration" --project Infrastructure.Persistence --startup-project WebApi --output-dir Migrations
dotnet ef database update --project Infrastructure.Persistence --startup-project WebApi
cd WebApi
dotnet run --launch-profile Local
```

4. On the Swagger page, execute the "Try it out" for the `/api/MyEntitys` route and note the warnings in the shell window.

I should note that I'm working on a Mac running macOS 11.1 (Big Sur) and dotnet 5.

If you're open to it, here is a possible solution:
https://github.com/pdevito3/craftsman/compare/master...nm777:default-sort-order
