### ISSUE TITLE
Error while scaffolding 

### ISSUE THREAD

**Issue by amalsharief** [pdevito3/craftsman#98]
Hi, thank you for your effort,

While I am running Craftsman,  I countered this error in the scaffolding stage :

Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
An exception of type 'System.IO.IOException' occurred in System.Private.CoreLib.dll but was not handled in user code
The process cannot access the file because it is being used by another process.

In this file 

D:\craftsman\craftsman\Craftsman\Builders\Features\AddUserFeatureOverrideModifier.cs

 at : line 117
115       // delete the old file and set the name of the new one to the original name
116       File.Delete(classPath.FullClassPath);
117       File.Move(tempPath, classPath.FullClassPath);

tempPath value :   d:\hr\SingleEntity\SingleEntityManagement\src\SingleEntityManagement\Domain\Users\Features\AddUser.cstemp
classPath.FullClassPat value :   d:\hr\SingleEntity\SingleEntityManagement\src\SingleEntityManagement\Domain\Users\Features\AddUser.cs

Am I doing something wrong  yaml file attached

Thank you in advance

[SingleEntity.yaml.txt](https://github.com/pdevito3/craftsman/files/9574213/SingleEntity.yaml.txt)

**Comment by pdevito3** [comment]
What version of Craftsman are you using? `AddUserFeatureOverrideModifier` is part of the upcoming release, so I'm assuming you're running this on latest in `develop`? I can try and take a look later today

**Comment by amalsharief** [comment]
Yes you are right the dev branch

Thank you

**Comment by pdevito3** [comment]
Your `Entities` data has an extra indent. The below should work!

Fwiw, hoping to move to a more type/format friendly setup for this at some point. There's JSON formatter logic that could be used to help yaml files like this, but need to do a rewrite of Craftsman at some point too, so might make a more lib friendly setup with C# support as well. Sorry for the hassle!

```yaml
DomainName: SingleEntity
BoundedContexts:
  - ProjectName: SingleEntityManagement
    Port: 5005
    DbContext:
      ContextName: SingleEntityDbContext
      DatabaseName: SingleEntityDb
      Provider: postgres
    Entities:
    - Name: SingleEntity
      Plural: SingleEntities
      Features:
        - Type: AddRecord
        - Type: GetRecord
        - Type: GetList
        - Type: UpdateRecord
        - Type: DeleteRecord
      Properties:
        - Name: Name
          Type: string
          CanFilter: true
          CanSort: true
    SwaggerConfig:
      Title: SingleEntity Management
      Description: SingleEntity desc
      ApiContact:
        Name: SingleEntity
        Email: devsupport@singleentity.com
        Url: 'https://www.singleentity.com'
    Environment:
      AuthSettings:
        Authority: 'http://localhost:3255/auth/realms/DevRealm'
        Audience: singlentity
        AuthorizationUrl: >-
          http://localhost:3255/auth/realms/DevRealm/protocol/openid-connect/auth
        TokenUrl: >-
          http://localhost:3255/auth/realms/DevRealm/protocol/openid-connect/token
        ClientId: singlentity.swagger
        ClientSecret: 974d6f71-d41b-4601-9a7a-a33081f80687
AuthServer:
  Name: KeycloakPulumi
  RealmName: DevRealm
  Port: 3255
  Clients:
    - Id: singlentity.postman.machine
      Name: SinglEntity Postman Machine
      Secret: 974d6f71-d41b-4601-9a7a-a33081f84682
      GrantType: ClientCredentials
      BaseUrl: 'https://oauth.pstmn.io/'
      Scopes:
        - singlentity
    - Id: singlentity.postman.code
      Name: SinglEntity Postman Code
      Secret: 974d6f71-d41b-4601-9a7a-a33081f84680
      GrantType: Code
      BaseUrl: 'https://oauth.pstmn.io/'
      Scopes:
        - singlentity
    - Id: singlentity.swagger
      Name: SinglEntity Swagger
      Secret: 974d6f71-d41b-4601-9a7a-a33081f80687
      GrantType: Code
      BaseUrl: 'https://localhost:5375/'
      Scopes:
        - singlentity
    - Id: singlentity.bff
      Name: SinglEntity BFF
      Secret: 974d6f71-d41b-4601-9a7a-a33081f80688
      BaseUrl: 'https://localhost:4378/'
      GrantType: Code
      RedirectUris:
        - 'https://localhost:4378/signin-oidc'
      AllowedCorsOrigins:
        - 'https://localhost:5375'
        - 'https://localhost:4378'
      Scopes:
        - singlentity
```
